#!/bin/sh
#                                                       -*- .bash_funtions -*-
# Copyright (C) (2003, 2011) Mauro N. Guerra.
#
# * 02/01/2006 re-write and cleanup.
# * 2008-2010  add-ons, fixes and cleanup.
# * 20/09/2011 export files to github, for better control of changes and improvements, plus version control.


# extraer algunos archivos
extract() {
if [ -f "$1" ] ; then
       case $1 in
         *.tar.bz2) tar xjf ;;
         *.tar.gz)  tar xzf $1 ;;
      *.tar.xz)  tar xJf $1 ;;
         *.bz2)     bunzip2 $1 ;;
         *.gz)      gunzip  $1 ;;
         *.tar)     tar xf  $1 ;;
         *.tbz2)    tar xjf $1 ;;
         *.tgz)     tar xzf $1 ;;
         *.7z)      7z x    $1 ;;
         *.Z)       uncompress ;;
         *.exe)     cabextract ;;
         *.rar)     unrar x $1 ;;
         *.xz)      unxz    $1 ;;
         *.zip)     unzip   $1 ;;
         *)     echo "$0: No puedo extraer $1: Que estas queriendo abrir?, no conosco el archivo"
      return 1
      ;;
       esac
else
       echo "$0: No puedo extraer $1: El archivo debe estar dañado"
       return 1
fi
return 0
}

# Para leer doc de toke
docview ()
{
  if [ -f $1 ] ; then
      case $1 in
          *.pdf)                             xpdf    $1  ;;
          *.ps|*.odt|*.doc)          abiword $1  ;;
          *.txt)                             leafpad $1  ;;
       *.png|*.jpg|*.jpeg|*.gif)     feh     $1  ;;
          *)   echo "No se como extraer '$1'..." ;;
      esac
  else
      echo "'$1' no es un archivo valido!"
  fi
}

# Comprimido de directorios rapido
mktar() { tar cf  "${1%%/}.tar"     "${1%%/}/"; }
mktgz() { tar czf "${1%%/}.tar.gz"  "${1%%/}/"; }
mktbz() { tar cjf "${1%%/}.tar.bz2" "${1%%/}/"; }

# Tunning para limpiar la pantalla
function clear ()
{
	tput clear
}

# algunos mods para grep
function psgrep ()
{
	ps -A | grep $1 | grep -v grep
}

# Una mescla de kill con ps
function pskill ()
{
	local pid

	pid=$(ps -A | grep $1 | grep -v grep | awk '{ print $1 }')
	echo -n "killing $1 (pid ${pid})... "
	kill -9 ${pid}
	echo "ok"
}

# Crear nuevos alias
function n-alias ()
{
	local name=$1
	local value="$2"

	echo alias ${name}=\'${value}\' >> ~/.bash_alias
	eval alias ${name}=\'${value}\'
	alias ${name}
}

# Mail pa afuera :P
function push ()
{
	pushd .
}


# Cuanta pila nos queda HAL???
function bat ()
{
	echo "Battery status: "
	cat /proc/acpi/battery/BAT0/state | grep "present"
	cat /proc/acpi/battery/BAT0/state | grep "charging state"
	cat /proc/acpi/battery/BAT0/info | grep "design capacity:"
	cat /proc/acpi/battery/BAT0/info | grep warning
	cat /proc/acpi/battery/BAT0/state | grep remaining
}


function ccopy ()
{ 
	cp $1 /tmp/ccopy.$1; 
}

function calc ()
{ 
	echo "${1}"|bc -l; 
}

# 2Do auto-completion

_todo()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    COMMANDS="add a addto addm append app archive command del  \
              rm depri dp do help list ls listall lsa listcon  \
              lsc listfile lf listpri lsp listproj lsprj move  \
              mv prepend prep pri p replace report"
    # Add custom commands from add-ons, if installed. 
    COMMANDS="$COMMANDS $('ls' ${TODO_ACTIONS_DIR:-$HOME/.todo.actions.d}/ 2>/dev/null)"
    OPTS="-@ -@@ -+ -++ -d -f -h -p -P -PP -a -n -t -v -vv -V -x"
    if [ "${cur:0:1}" == "+" ]; then
        completions="$(t listproj)"
    elif [ "${cur:0:1}" == "@" ]; then
        completions="$(t listcon)"
    elif [ $COMP_CWORD -eq 1 ]; then
        completions="$COMMANDS $OPTS"
    else
        case "${prev}" in
            -*) completions="$COMMANDS $OPTS";;
            *)  return 0;;
        esac
    fi
    COMPREPLY=( $( compgen -W "$completions" -- $cur ))
    return 0
}
complete -F _todo todo.sh
# If you define an alias (e.g. "t") to todo.sh, you need to explicitly enable
# completion for it, too: 
complete -F _todo 2do
complete -F _todo 2do