#!/bin/sh
#                                                       -*- .bash_alias -*-
# Copyright (C) (2007, 2011) Mauro N. Guerra.
#
# * 2008-2010  add-ons, fixes and cleanup.
# * 20/09/2011 export files to github, for better control of changes and improvements, plus version control.


# Algunos alias
alias resource='source ~/.bashrc'
alias t='todo.sh -d ~/local/2do/todo.cfg'
alias cpaste="ls /tmp/ccopy* | sed 's|[^\.]*.\.||' | xargs -I % mv /tmp/ccopy.% ./%"
alias ls='ls -F --color'
alias l='ls -l -F --color'
alias la='ls -a -F --color'
alias logout='clear && logout'
alias j='joe'
alias ll='ls -lh -a -F --color'
alias cdp='cd /home/pub/'
alias cd..='cd ..'
alias msg='sudo tail -f /var/log/messages'
alias gmail='fetchmail -v -m "procmail -d %T"'
alias less='less -x 4'
alias rbak='rm *~'
alias cdw='cd ~/local/work'
alias sshot='import -window root shot-$(date +%Y%m%d%k%M).jpg'
alias dirf='find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"'
alias clasicos="history | awk '{print $2}' | sort | uniq -c | sort -rn | head "

# Disk
alias dff='df -x devtmpfs -x tmpfs -h | column -t'
alias duu="du -h -d 1 | sed -e 's/\.\///g' -e 's/\.$/<-- Total dir size/'"
