#!/bin/sh
#                                                       -*- .bash_funtions -*-
# Copyright (C) (2003, 2011) Mauro N. Guerra.
#
# * 02/01/2006 re-write and cleanup.
# * 2008-2010  add-ons, fixes and cleanup.
# * 20/09/2011 export files to github, for better control of changes and improvements, plus version control.


function clear ()
{
	tput clear
}

function psgrep ()
{
	ps -A | grep $1 | grep -v grep
}

function pskill ()
{
	local pid

	pid=$(ps -A | grep $1 | grep -v grep | awk '{ print $1 }')
	echo -n "killing $1 (pid ${pid})... "
	kill -9 ${pid}
	echo "ok"
}

function n-alias ()
{
	local name=$1
	local value="$2"

	echo alias ${name}=\'${value}\' >> ~/.bash_alias
	eval alias ${name}=\'${value}\'
	alias ${name}
}

function push ()
{
	pushd .
}


function bat ()
{
	echo "Battery status: "
	cat /proc/acpi/battery/BAT0/state | grep "present"
	cat /proc/acpi/battery/BAT0/state | grep "charging state"
	cat /proc/acpi/battery/BAT0/info | grep "design capacity:"
	cat /proc/acpi/battery/BAT0/info | grep warning
	cat /proc/acpi/battery/BAT0/state | grep remaining
}

function ccopy ()
{ 
	cp $1 /tmp/ccopy.$1; 
}

function calc ()
{ 
	echo "${1}"|bc -l; 
}

# 2Do auto-completion

_todo()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    COMMANDS="add a addto addm append app archive command del  \
              rm depri dp do help list ls listall lsa listcon  \
              lsc listfile lf listpri lsp listproj lsprj move  \
              mv prepend prep pri p replace report"
    # Add custom commands from add-ons, if installed. 
    COMMANDS="$COMMANDS $('ls' ${TODO_ACTIONS_DIR:-$HOME/.todo.actions.d}/ 2>/dev/null)"
    OPTS="-@ -@@ -+ -++ -d -f -h -p -P -PP -a -n -t -v -vv -V -x"
    if [ "${cur:0:1}" == "+" ]; then
        completions="$(t listproj)"
    elif [ "${cur:0:1}" == "@" ]; then
        completions="$(t listcon)"
    elif [ $COMP_CWORD -eq 1 ]; then
        completions="$COMMANDS $OPTS"
    else
        case "${prev}" in
            -*) completions="$COMMANDS $OPTS";;
            *)  return 0;;
        esac
    fi
    COMPREPLY=( $( compgen -W "$completions" -- $cur ))
    return 0
}
complete -F _todo todo.sh
# If you define an alias (e.g. "t") to todo.sh, you need to explicitly enable
# completion for it, too: 
complete -F _todo 2do
complete -F _todo 2do